#################################
###                           ###
###         JASON TODD        ###
###                           ###
#################################


#hyprland
activeColor     = "#a67356"

#waybar
activeWorkspace = "#a61b11"


