











source = ~/.config/hypr/config/binds.config
source = ~/.config/hypr/config/monitors.config
source = ~/.config/hypr/config/autostart.config
source = ~/.config/hypr/config/enviromentVar.config
source = ~/.config/hypr/config/permissions.config
source = ~/.config/hypr/config/lookANDfeel.config
source = ~/.config/hypr/config/input.config
source = ~/.config/hypr/config/windowsANDworkspaces.config
